Repository Future-House/aviary, pull requests merged in 2024-10, with the labels that each got.

#94 Updated messages explanatory table
  README.md
Labels: documentation, size:S

#91 Aviary Environment Building Tutorial
  docs/Building Environments in Aviary.ipynb
  pyproject.toml
Labels: documentation, size:L

#95 aviary.core.EnvStateMessage
  src/aviary/core.py
Labels: size:XS

#98 Moving from `large-runner` to `ubuntu-latest` for CI
  .github/workflows/tests.yml
  uv.lock
Labels: bug, size:XS

#99 HotPotQA lookup returns the wrong result is asked to look up the same term in 2 different pages sequentially
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
Labels: bug, size:M

#102 Add EvalAnswerMode to HotPotQAEnv
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
  src/aviary/core.py
  src/aviary/tools/__init__.py
Labels: enhancement, size:M

#103 Fix eval mode setting in config
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
Labels: bug, size:S

#104 Unify answer tool naming
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
Labels: size:M
