Repository Future-House/aviary, pull requests merged in 2024-12, with the labels that each got.

#132 Implements new functional syntax
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  src/aviary/core.py
  src/aviary/functional.py
  tests/test_functional.py
  uv.lock
Labels: enhancement, size:L

#135 Fixed `codeflash`'s `formatter-cmds`
  pyproject.toml
  uv.lock
Labels: bug, enhancement, size:XS

#140 Added complex types to str
  src/aviary/tools/base.py
  tests/test_tools.py
Labels: enhancement, size:M

#141 Tool exection timeout
  src/aviary/env.py
  tests/test_envs.py
Labels: size:M

#142 Moved eval_answer from tools to core
  packages/hotpotqa/tests/test_hotpotqa_env.py
  src/aviary/core.py
  src/aviary/tools/__init__.py
  src/aviary/tools/utils.py
  src/aviary/utils.py
Labels: size:L

#143 Type hinted `maybe_wait_for` return
  src/aviary/env.py
Labels: enhancement, size:XS

#144 Clean codeflash.yml config
  .github/workflows/codeflash.yml
Labels: size:S

#147 Populated `LICENSE`
  LICENSE
Labels: bug, size:XS

#150 Import as written in readme for functional doesn't work
  README.md
Labels: documentation, size:XS

#151 Support multiple images
  .github/workflows/tests.yml
  .python-version
  src/aviary/message.py
  src/aviary/utils.py
  tests/fixtures/test_images/sample_image1.b64
  tests/test_messages.py
  uv.lock
Labels: enhancement, size:L

#152 minor adjustment to image testing to support png
  .mailmap
  .pre-commit-config.yaml
  src/aviary/message.py
  src/aviary/utils.py
  tests/fixtures/test_images/sample_jpeg_image.b64
  tests/fixtures/test_images/sample_png_image.b64
  tests/test_messages.py
Labels: enhancement, size:S

#154 Renovate `lockFileMaintenance` respecting `schedule` and 2-week stability period
  .github/renovate.json5
Labels: enhancement, size:XS

#156 `eval_answer` allowing for `str | EvalAnswerMode` not just `EvalAnswerMode`
  src/aviary/utils.py
  tests/test_utils.py
Labels: enhancement, size:S

#158 Updated description of content
  README.md
Labels: documentation, size:S
