Repository Future-House/aviary, pull requests merged in 2024-11, with the labels that each got.

#113 Python 3.13 support
  .github/workflows/tests.yml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S

#114 Replacing `list[Messages]` with `Messages` in environments
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  src/aviary/env.py
Labels: size:M

#109 Moving to `uv` dependency groups
  .github/workflows/codeflash.yml
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S

#110 Removed unused `SQLAlchemy` dev dependency
  pyproject.toml
  uv.lock
Labels: bug, size:XS

#107 HotPotQA better `search` tool failure message
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
Labels: enhancement, size:XS

#120 Adding `fetch-depth` to `actions/checkout` to fix CI
  .github/workflows/tests.yml
Labels: bug, size:XS

#115 Added invalid tool checker
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  pyproject.toml
  src/aviary/env.py
  src/aviary/render.py
  src/aviary/tools/argref.py
  src/aviary/tools/server.py
  tests/test_envs.py
Labels: enhancement, size:M

#122 Fixing sorting of `not ordered` tool calls
  src/aviary/env.py
Labels: bug, size:S

#126 Opting into `ruff` preview rules and `validate-pyproject-schema-store` hook swap
  .pre-commit-config.yaml
  docs/Building Environments in Aviary.ipynb
  pyproject.toml
  src/aviary/tools/base.py
Labels: enhancement, size:M

#123 Renamed `Environment.exec_tool_calls` `ordered` to `concurrency`
  src/aviary/env.py
  tests/test_envs.py
Labels: enhancement, size:M

#127 Generic TaskDataset server/client
  .pre-commit-config.yaml
  src/aviary/core.py
  src/aviary/dataset_server.py
  src/aviary/env.py
  src/aviary/env_client.py
  tests/test_envs.py
Labels: enhancement, size:L

#128 `mypy` ignoring `cloudpickle` as it's untyped
  pyproject.toml
Labels: bug, size:XS

#130 Handling `ordered` deprecation
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  src/aviary/env.py
Labels: size:XS

#131 Making uvicorn import lazy
  src/aviary/dataset_server.py
Labels: enhancement, size:S
