Repository Future-House/aviary, pull requests merged in 2025-03, with the labels that each got.

#211 Updated tooling versions and configs
  .pre-commit-config.yaml
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/litqa/src/aviary/envs/litqa/env.py
  packages/litqa/src/aviary/envs/litqa/task.py
  packages/litqa/tests/test_litqa_env.py
  pyproject.toml
  src/aviary/dataset_server.py
  src/aviary/env.py
  src/aviary/env_client.py
  src/aviary/message.py
  src/aviary/render.py
  src/aviary/tools/utils.py
  src/aviary/utils.py
  tests/test_utils.py
Labels: enhancement, size:L

#169 Remove newline filter in param descriptions for agents
  src/aviary/tools/base.py
  tests/test_tools.py
Labels: size:M

#214 Simplified `refurb` in CI after #196 fixed `mypy` config
  .github/workflows/tests.yml
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/lfrqa/tests/test_lfrqa_env.py
Labels: enhancement, size:S
