Repository Future-House/aviary, pull requests merged in 2025-09, with the labels that each got.

#279 Testing `functools.wraps`'d tools
  pyproject.toml
  tests/test_tools.py
  uv.lock
Labels: enhancement, size:M

#280 Notebook env
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  README.md
  packages/notebook/README.md
  packages/notebook/docker/Dockerfile.pinned
  packages/notebook/docker/install_IRKernel.R
  packages/notebook/docker/requirements.txt
  packages/notebook/pyproject.toml
  packages/notebook/src/aviary/envs/notebook/__init__.py
  packages/notebook/src/aviary/envs/notebook/config.py
  packages/notebook/src/aviary/envs/notebook/env.py
  packages/notebook/src/aviary/envs/notebook/py.typed
  packages/notebook/src/aviary/envs/notebook/utils.py
  packages/notebook/tests/test_nb_env.py
  pyproject.toml
  uv.lock
Labels: enhancement, size:XXL

#282 Add publish step for aviary.notebook
  .github/workflows/publish.yml
Labels: size:XS

#284 Removing `__future__ import annotations` from `message.py`
  src/aviary/message.py
Labels: enhancement, size:XS

#288 Catch EnvironmentClient errors
  src/aviary/env_client.py
Labels: enhancement, size:M

#291 Only close NBEnv state if it exists
  packages/notebook/src/aviary/envs/notebook/env.py
Labels: bug, size:XS

#296 Fixed `partial_format` working with partial variables
  src/aviary/utils.py
  tests/test_utils.py
Labels: bug, size:M
