Repository Future-House/aviary, pull requests merged in 2025-02, with the labels that each got.

#185 Add question_id functionality to mcq object
  src/aviary/utils.py
  tests/test_utils.py
Labels: enhancement, size:M

#186 Allowing latest LiteLLM by handling latent `None` content error
  pyproject.toml
  src/aviary/utils.py
  uv.lock
Labels: bug, size:XS

#188 Allowing null `FunctionInfo.parameters` to support `gemini-1.5-flash` agents
  pyproject.toml
  src/aviary/env.py
  src/aviary/tools/base.py
  tests/cassettes/TestParallelism.test_dummyenv_using_empty_params.yaml
  tests/conftest.py
  tests/test_envs.py
  tests/test_tools.py
Labels: enhancement, size:L

#194 Fixed latent `NoneType` error in tool server after #188
  src/aviary/tools/server.py
Labels: bug, size:M

#195 Added classifiers to gsmk8 and hotpotqa
  packages/gsm8k/pyproject.toml
  packages/hotpotqa/pyproject.toml
Labels: size:S

#191 Migrate lfrqa from paper-qa
  .github/workflows/publish.yml
  README.md
  packages/lfrqa/README.md
  packages/lfrqa/pyproject.toml
  packages/lfrqa/src/aviary/envs/lfrqa/__init__.py
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/src/aviary/envs/lfrqa/py.typed
  packages/lfrqa/src/aviary/envs/lfrqa/task.py
  packages/lfrqa/tests/stub_data/mini_lfrqa.csv
  packages/lfrqa/tests/test_lfrqa_env.py
  pyproject.toml
  uv.lock
Labels: size:L

#196 Configure mypy to run locally and fix new errors
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/gsm8k/tests/test_gsm8k_env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
  pyproject.toml
  src/aviary/env.py
  src/aviary/functional.py
  src/aviary/message.py
  src/aviary/tools/base.py
  src/aviary/tools/server.py
  tests/test_envs.py
  tests/test_tools.py
Labels: size:M

#190 Migrate LitQA and LFRQA from paper-qa
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .mailmap
  .pre-commit-config.yaml
  README.md
  packages/lfrqa/README.md
  packages/lfrqa/pyproject.toml
  packages/lfrqa/src/aviary/envs/lfrqa/__init__.py
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/src/aviary/envs/lfrqa/py.typed
  packages/lfrqa/src/aviary/envs/lfrqa/task.py
  packages/lfrqa/tests/stub_data/mini_lfrqa.csv
  packages/lfrqa/tests/test_lfrqa_env.py
  packages/litqa/README.md
  packages/litqa/pyproject.toml
  packages/litqa/src/aviary/envs/litqa/__init__.py
  packages/litqa/src/aviary/envs/litqa/env.py
  packages/litqa/src/aviary/envs/litqa/py.typed
  packages/litqa/src/aviary/envs/litqa/task.py
  packages/litqa/tests/cassettes/TestTaskDataset.test_tool_failure.yaml
  packages/litqa/tests/conftest.py
  packages/litqa/tests/stub_data/bates.txt
  packages/litqa/tests/stub_data/flag_day.html
  packages/litqa/tests/stub_data/paper.pdf
  packages/litqa/tests/test_litqa_env.py
  pyproject.toml
  src/aviary/core.py
  uv.lock
Labels: enhancement, size:XXL

#198 `git checkout` before `pre-commit`
  .github/workflows/tests.yml
Labels: bug, size:XS

#201 Updated litqa and lfrqa to lmi
  packages/lfrqa/pyproject.toml
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/src/aviary/envs/lfrqa/task.py
  packages/litqa/pyproject.toml
  packages/litqa/src/aviary/envs/litqa/env.py
  packages/litqa/src/aviary/envs/litqa/task.py
  packages/litqa/tests/conftest.py
  pyproject.toml
  uv.lock
Labels: size:M

#203 Fixed `README` imports for LitQA `TASK_DATASET_NAME`
  packages/litqa/README.md
Labels: bug, documentation, size:XS

#206 `LitQATaskDataset` also storing LitQA question ID
  packages/litqa/src/aviary/envs/litqa/task.py
  packages/litqa/tests/test_litqa_env.py
  src/aviary/utils.py
Labels: enhancement, size:M

#208 Make LFRQAQuestion inherit from MultipleChoiceQuestion
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/src/aviary/envs/lfrqa/task.py
  packages/lfrqa/tests/test_lfrqa_env.py
Labels: enhancement, size:L

#210 Removed relative path in `test_lfrqa_env.py`
  packages/lfrqa/tests/test_lfrqa_env.py
Labels: bug, size:S

#209 Not clobbering `Docs` in `LFRQAPairwiseEvalEnv`
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/src/aviary/envs/lfrqa/task.py
Labels: bug, size:S
