Repository Future-House/aviary, pull requests merged in 2025-07, with the labels that each got.

#260 Fixed `uv==0.8.0`+ BAIPP breaking `lint` CI
  .github/workflows/tests.yml
Labels: bug, size:XS

#257 Fixed LFRQA not being in available envs
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/tests/test_lfrqa_env.py
Labels: bug, enhancement, size:XS

#259 Removed duplicated `TEvaluation` from LitQA
  packages/litqa/src/aviary/envs/litqa/env.py
  packages/litqa/src/aviary/envs/litqa/task.py
Labels: bug, size:S

#261 Downpinning `datasets` for its `trust_remote_code` deprecation
  packages/hotpotqa/pyproject.toml
  uv.lock
Labels: bug, size:XS

#263 Removed `codeflash`
  .github/workflows/codeflash.yml
  pyproject.toml
  uv.lock
Labels: size:M

#265 Propagating #260 to publish CI
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: bug, size:M

#267 Check state order dependence
  tests/test_tools.py
Labels: size:M

#268 Improved multimodal message docs
  src/aviary/message.py
Labels: documentation, size:S
