Repository Future-House/aviary, pull requests merged in 2025-08, with the labels that each got.

#270 Lower pinning `datasets` to ensure modern `pyarrow` compatibility
  packages/gsm8k/pyproject.toml
  packages/hotpotqa/pyproject.toml
  packages/litqa/pyproject.toml
  uv.lock
Labels: bug, size:XS

#269 Exposing LLM configuration in `MultipleChoiceQuestion.grade`
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  src/aviary/utils.py
Labels: enhancement, size:S

#273 Deprecate open answer from MultipleChoiceQuestion
  pyproject.toml
  src/aviary/utils.py
  tests/test_utils.py
Labels: size:M

#278 Env var to log `exec_tool_calls` exceptions with traceback at error level
  src/aviary/env.py
Labels: bug, enhancement, size:S
