Repository Future-House/aviary, pull requests merged in 2025-05, with the labels that each got.

#223 fix: KeyError: 'unsure' with LFRQAPairwiseEvalEnv
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
Labels: bug, size:XS

#225 Pulled in latest `httpx` in `dev`
  pyproject.toml
  tests/test_envs.py
  uv.lock
Labels: bug, size:XS

#224 LFRQA using `grading_rewards` and using `Enum` for rewards implementation
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/src/aviary/envs/lfrqa/task.py
Labels: bug, enhancement, size:M

#228 Removed `httpx` constraint from Renovate config
  .github/renovate.json5
Labels: enhancement, size:XS

#230 Improving README and Docs
  README.md
  citation.bib
  docs/assets/aviary_art.png
  packages/gsm8k/README.md
  packages/hotpotqa/README.md
  packages/lfrqa/README.md
  packages/litqa/README.md
  pyproject.toml
  tutorials/Building a Custom Environment in Aviary.ipynb
  tutorials/Building a GSM8k Environment in Aviary.ipynb
  uv.lock
Labels: documentation, size:XL

#232 Update README.md
  README.md
Labels: documentation, size:XS
