Repository Future-House/aviary, pull requests merged in 2025-04, with the labels that each got.

#215 Open sourcing environment code
  packages/cloning/.gitignore
  packages/cloning/README.md
  packages/cloning/build_poly_tools.sh
  packages/cloning/cloning/__init__.py
  packages/cloning/cloning/app.py
  packages/cloning/cloning/clients/__init__.py
  packages/cloning/cloning/clients/annotator_client.py
  packages/cloning/cloning/clients/poly_client.py
  packages/cloning/cloning/clients/search_client.py
  packages/cloning/cloning/dataset.py
  packages/cloning/cloning/env.py
  packages/cloning/cloning/enzymes.py
  packages/cloning/cloning/poly_local.py
  packages/cloning/cloning/py.typed
  packages/cloning/cloning/sequence_models.py
  packages/cloning/cloning/task_proteins.py
  packages/cloning/cloning/transforms.py
  packages/cloning/remote/annotator.py
  packages/cloning/remote/annotator_lib/annotate.sh
  packages/cloning/remote/annotator_lib/annotation2gbk.py
  packages/cloning/remote/databases.sh
  packages/cloning/remote/dependencies.py
  packages/cloning/remote/deploy.py
  packages/cloning/remote/hot_plasmids.py
  packages/cloning/remote/models.py
  packages/cloning/remote/poly.py
  packages/cloning/remote/poly_lib/clone.go
  packages/cloning/remote/poly_lib/gibson.go
  packages/cloning/remote/poly_lib/orf.go
  packages/cloning/remote/poly_lib/primers.go
  packages/cloning/remote/poly_lib/synthesize.go
  packages/cloning/remote/project-bio-deploy.py
  packages/cloning/remote/search.py
  packages/cloning/tests/test_clients.py
  packages/cloning/tests/test_datasets.py
  packages/cloning/tests/test_env.py
  packages/cloning/tests/test_poly_local.py
  packages/cloning/tests/test_transforms.py
  packages/cloning/tests/test_types.py
  packages/protein-stability/README.md
  packages/protein-stability/apis/api_cartddg.py
  packages/protein-stability/apis/api_esm.py
  packages/protein-stability/apis/api_prody.py
  packages/protein-stability/apis/api_rosetta.py
  packages/protein-stability/download_pdb.py
  packages/protein-stability/find_conserved.py
  packages/protein-stability/process_data.py
  packages/protein-stability/protein_stability/__init__.py
  packages/protein-stability/protein_stability/dataset.py
  packages/protein-stability/protein_stability/environment.py
  packages/protein-stability/protein_stability/expts_sn/ei.py
  packages/protein-stability/protein_stability/expts_sn/eval.py
  packages/protein-stability/protein_stability/inference_apis.py
  packages/protein-stability/protein_stability/rewards.py
  packages/protein-stability/protein_stability/state.py
  packages/protein-stability/protein_stability/tools.py
  packages/protein-stability/tests/mock_data/example.fasta
  packages/protein-stability/tests/mock_data/example.pdb
  packages/protein-stability/tests/mock_data/example.txt
  packages/protein-stability/tests/test_stability_tools.py
Labels: size:XXL

#216 Added question info to `HotPotQAEnv.export_frame`
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
Labels: enhancement, size:XS

#218 Modern Python 3.13 in CI and latest tooling
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: enhancement, size:S

#219 Updated repo badges
  README.md
Labels: documentation, size:XS

#220 Removed unnecessary `pytest_asyncio.fixture`
  pyproject.toml
  tests/test_envs.py
  uv.lock
Labels: bug, size:XS
