Repository Future-House/aviary, pull requests merged in 2025-06, with the labels that each got.

#237 Giving `Agent`s insight into `ExceptionGroup`s
  src/aviary/env.py
  src/aviary/utils.py
  tests/test_envs.py
Labels: bug, enhancement, size:M

#238 Added missing PyPI classifiers
  packages/gsm8k/pyproject.toml
  packages/hotpotqa/pyproject.toml
  packages/lfrqa/pyproject.toml
  packages/litqa/pyproject.toml
  pyproject.toml
Labels: documentation, enhancement, size:S

#239 Fixed missing `None` unions in `Frame` serialization code
  src/aviary/env.py
  tests/test_envs.py
Labels: bug, size:XS

#244 Pinned latest `litellm` for `tool_choice=Tool`'s `finish_reason` fix
  pyproject.toml
  src/aviary/tools/utils.py
  uv.lock
Labels: enhancement, size:XS

#246 Add safe eval expression function
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/gsm8k/tests/test_gsm8k_env.py
Labels: enhancement, size:L

#235 Update: Building a Custom Environment in Aviary.ipynb and safe eval function.
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/gsm8k/tests/test_gsm8k_env.py
  tutorials/Building a Custom Environment in Aviary.ipynb
  tutorials/Building a GSM8k Environment in Aviary.ipynb
Labels: documentation, size:XL

#243 Update tutorial links in README.md to reflect new paths
  README.md
Labels: documentation, size:XS

#182 Created async `Environment.get_id` method for unique environment ID
  packages/gsm8k/src/aviary/envs/gsm8k/env.py
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
  packages/lfrqa/src/aviary/envs/lfrqa/env.py
  packages/lfrqa/tests/test_lfrqa_env.py
  packages/litqa/src/aviary/envs/litqa/env.py
  packages/litqa/tests/test_litqa_env.py
  src/aviary/env.py
  tests/conftest.py
  tests/test_envs.py
Labels: enhancement, size:M

#242 Partially fixed doctests in `HotPotQAEnv`
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
Labels: bug, size:M

#251 Allowing `litellm<1.72` in `llm` extra for working VCR
  pyproject.toml
  src/aviary/tools/utils.py
  tests/cassettes/TestParallelism.test_dummyenv_using_empty_params.yaml
  tests/cassettes/TestParallelism.test_tool_selector_from_model_name[gpt-4o-mini-2024-07-18].yaml
  tests/cassettes/TestParallelism.test_tool_selector_with_external_acompletion[gpt-4o-mini-2024-07-18].yaml
  uv.lock
Labels: bug, size:L

#252 Rolling out `markdownlint-cli` to lint Markdown
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  packages/gsm8k/README.md
  packages/lfrqa/README.md
  packages/litqa/README.md
  pyproject.toml
Labels: documentation, enhancement, size:L
