Repository Future-House/aviary, pull requests merged in 2025-01, with the labels that each got.

#166 Testing `in` check with `Frame`
  tests/test_envs.py
Labels: enhancement, size:S

#170 Latest tooling and fixed some test warnings
  .pre-commit-config.yaml
  packages/hotpotqa/tests/test_hotpotqa_env.py
  pyproject.toml
  src/aviary/tools/base.py
  src/aviary/tools/server.py
  tests/test_envs.py
  tests/test_functional.py
  tests/test_tools.py
  uv.lock
Labels: enhancement, size:M

#173 Forbid extra arguments in configuration
  src/aviary/utils.py
Labels: enhancement, size:XS

#172 Pulling in Ruff 0.9
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_envs.py
  tests/test_tools.py
Labels: enhancement, size:M

#175 Allowing open answer prompting with `MultipleChoiceQuestion`
  src/aviary/core.py
  src/aviary/utils.py
  tests/test_utils.py
Labels: enhancement, size:M

#177 Allowing `random.Random` seed and documenting `TaskDataset` shuffling risk
  .pre-commit-config.yaml
  pyproject.toml
  src/aviary/utils.py
  tests/test_utils.py
  uv.lock
Labels: documentation, enhancement, size:M

#178 Removed `arbitrary_types_allowed=True` from `MultipleChoiceQuestion` via custom Pydantic serializer/validator
  pyproject.toml
  src/aviary/utils.py
  tests/test_utils.py
Labels: enhancement, size:M

#180 Added a `CITATION.cff`
  CITATION.cff
Labels: documentation, enhancement, size:XS

#179 `RandomAnnotation` support for `model_dump(mode="json")`
  src/aviary/utils.py
  tests/test_utils.py
Labels: bug, enhancement, size:M

#181 Added question ID to `HotPotQAEnv`
  packages/hotpotqa/src/aviary/envs/hotpotqa/env.py
  packages/hotpotqa/tests/test_hotpotqa_env.py
Labels: enhancement, size:M

#183 Moved `DummyEnv` to report empty `ToolRequestMessage`
  src/aviary/env.py
  tests/test_envs.py
Labels: bug, size:XS
